Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'sha256-dFmytIpEsKMlTVFczltfchCGf7an8K5vGQxf7zgTEbU='; img-src 'self' data:; connect-src 'self'; media-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Referrer-Policy: strict-origin-when-cross-origin
